name: CI

on:
  push:
    branches:
      - main
      - master
      - feature/*

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
            **/.eslintcache
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install modules
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Check types
        run: yarn check:types

      - name: Lint
        run: yarn lint

      - name: Run tests
        run: yarn test
