name: CI

on:
  push:
    branches:
      - main
      - master
      - feature/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-commit-check
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline --production=false

      - name: Turbo Cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}

      - name: Build
        run: yarn build

      - name: Check types
        run: yarn check:types

      - name: Lint
        run: yarn lint

      - name: Run tests
        run: yarn test
